project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1: A Layered Grammar of Graphics: ggplot2 methods"
        href: "../Hands-on_Exercise/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-on Exercise 2: Beyond ggplot2 Fundamentals" 
        href: "../Hands-on_Exercise/Hands-on_Ex02/Hands-on_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - superhero
      - brand
    css: styles.css
    toc: true

editor: visual

