{
  "hash": "606bb7ba28c3844151be6b9add2cae00",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home_Exercise 01\"\nauthor: \"Albert Chia\"\ndate: \"May 21, 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contents\"\n    toc-location: left\n    code-fold: true\n    code-summary: \"Show code\"\n    code-tools: true\n    code-overflow: wrap\n    fig-width: 10\n    fig-height: 6\n    fig-align: center\n    embed-resources: true\n    fontsize: 1rem\n    page-layout: full\neditor: visual\n---\n\n# Visual Analytics for Insurance Data Discovery\n\n## 1. Overview\n\nInsurance companies collect detailed records on every policy they issue, including the type of vehicle insured, the policyholder's profile, premiums charged, and claims paid out. Despite this wealth of data, the root causes of poor portfolio profitability and high claims volatility often remain unknown, as traditional reporting tools such as dashboards provide only surface-level summaries.\n\nVisual analytics is the integration of data visualisation, statistics, and data mining, offering a more powerful approach. By combining human pattern recognition with computational analysis through appropriate visual interfaces, it enables analysts to discover unexpected patterns and support more effective data-driven decisions.\n\n### 1.1. Objectives\n\nThis study applies visual analytics techniques in R to a real-world motor vehicle insurance portfolio from a Spanish non-life insurer.\n\nThe specific objectives of this study are:\n\n- To explore the distributions and characteristics of key numerical and categorical variables through *univariate visual analysis*.\n\n- To investigate and statistically validate factors influencing the profitability and volatility of the portfolio through *bivariate analysis*.\n\n## 2. The Data\n\nThe dataset used in this study is a real-world motor vehicle insurance portfolio from a Spanish insurance company specialising in non-life insurance. It is publicly available at [Mendeley Data](https://data.mendeley.com/datasets/sw4jmdb2sm/1) and comes with a data cookbook that describes each variable.\n\nThe dataset contains policy-level records with information across three broad categories:\n\n- **Policy characteristics** — vehicle type, vehicle age, coverage type, and geographic zone\n- **Policyholder information** — driver age group and years of seniority with the insurer\\\n- **Financial outcomes** — earned premium, number of claims, and total claim amount\n\nThese variables allow us to examine both the composition of the portfolio and the financial performance of each segment.\n\n## 3. Getting Started\n\n### 3.1 Loading R Packages\n\nTHe following R packages are loaded using `pacman::p_load()`, which automatically installs any missing packages before loading them.\n\n- **tidyverse**: Core collection of R packages for data wrangling and visualisation, including ggplot2, dplyr, tidyr, readr, and forcats.\n- **ggstatsplot**: Extends ggplot2 by embedding statistical test results directly within plots.\n- **ggdist**: Provides geoms for visualising distributions and uncertainty.\n- **ggridges**: Provides geoms for creating ridgeline plots, useful for visualising distributional changes across groups or time periods.\n- **GGally**: Extends ggplot2 with pairwise plot matrices via `ggpairs()`.\n- **patchwork**: Combines multiple ggplot2 plots into a single layout.\n- **ggthemes**: Provides additional clean themes for ggplot2.\n- **scales**: Formats axis labels with commas, percentages, and currencies.\n- **knitr**: Formats tables neatly within the HTML output.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npacman::p_load(tidyverse, ggstatsplot, ggdist, ggridges, GGally, patchwork, ggthemes, scales, knitr)\n```\n:::\n\n\n## 4. Data Wrangling\n\n### 4.1 Importing the Data\n\nDatasets in CSV format are typically imported using `read_csv()`. However, this dataset originates from a Spanish insurance company and uses a semicolon (`;`) as the column delimiter — a common European convention where the comma is reserved as the decimal separator. Initial inspection suggested `read_csv2()` would be appropriate, as it is specifically designed for semicolon-delimited files and assumes European decimal formatting.\n\nHowever, diagnostic checks on the raw character values of numeric columns revealed that this dataset uses a **period as the decimal separator** despite the semicolon delimiter — an inconsistency with strict European format. When `read_csv2()` was applied, it incorrectly treated the decimal period as a thousands grouping mark and stripped it, inflating values such as `279.56` into `279,557,557,563,945` — rendering all premium and incurred columns unusable.\n\nTo resolve this, `read_delim()` is used instead, with an explicit locale specifying period as the decimal mark and no grouping mark. This correctly parses all numeric columns while preserving the semicolon as the field delimiter.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\ninsurance <- read_delim(\n  \"data/motor_insurance.csv\",\n  delim  = \";\",\n  locale = locale(decimal_mark = \".\", grouping_mark = \"\")\n)\nglimpse(insurance)\n```\n:::\n\n\n### 4.2 Checking for Missing Values\n\nBefore any transformation, we check for missing values across all columns. This ensures we understand the completeness of the data before making decisions about how to handle gaps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(),\n               names_to = \"variable\",\n               values_to = \"missing_count\") %>%\n  filter(missing_count > 0) %>%\n  arrange(desc(missing_count))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  variable            missing_count\n  <chr>                       <int>\n1 fuel_type                    1287\n2 vehicle_value                 513\n3 vehicle_age                     2\n4 age_driving_licence             2\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Note\n\n- Four variables were found to contain missing values, as shown in the table above. The highest proportion of missing data is in `fuel_type` (1,287 records missing - 0.36% of all policies), followed by `vehicle_value` (513 records missing - 0.14%). The remaining two variables each have fewer than 100 missing entries, insignificant of the dataset.\n- Given that all missing values represent very small proportions of the total 354,140 records, and that several of these variables are not central to our profitability analysis, no imputation is performed. Records with missing values in variables used in specific analyses will be excluded at the point of use.\n:::\n\n### 4.3 Selecting Relevant Variables\n\nThe dataset contains 47 variables. For this study, we focus on variables directly relevant to exploring portfolio composition and profitability. Coverage-specific breakdowns of premiums, claims and incurred costs are excluded in favour of their totals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_selected <- insurance %>%\n  select(insured_id, year, policy_type, policy_status, business_type, payment_frequency, bonus_score,\n         driver_age, vehicle_age, fuel_type, vehicle_value, municipality_type, circulation_area,\n         total_premium, total_claims, total_incurred, total_exposure)\n```\n:::\n\n\n### 4.4 Converting Categorical Variables to Factors\n\nSeveral variables are stored as character codes. We convert these to factors with meaningful labels based on the data cookbook, so they display correctly in all visualisations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_selected <- insurance_selected %>%\n  mutate(\n    policy_type = factor(policy_type,\n                         levels = c(\"TP\", \"TPG\", \"CC\", \n                                    \"COMP_E\", \"COMP_N\"),\n                         labels = c(\"Third-party\",\n                                    \"Third-party + Glass\",\n                                    \"Third-party + Combined\",\n                                    \"Comprehensive (excess)\",\n                                    \"Comprehensive (no excess)\")),\n    \n    policy_status = factor(policy_status,\n                           levels = c(\"A\", \"C\"),\n                           labels = c(\"Active\", \"Cancelled\")),\n    \n    business_type = factor(business_type,\n                           levels = c(\"NB\", \"P\"),\n                           labels = c(\"New Business\", \"Portfolio\")),\n    \n    payment_frequency = factor(payment_frequency,\n                               levels = c(\"A\", \"S\", \"Q\"),\n                               labels = c(\"Annual\", \n                                          \"Semiannual\", \n                                          \"Quarterly\")),\n    \n    bonus_score = factor(bonus_score,\n                         levels = c(\"G\", \"N\", \"B\"),\n                         labels = c(\"Good\", \"Neutral\", \"Bad\")),\n    \n    fuel_type = factor(fuel_type,\n                       levels = c(\"D\", \"G\"),\n                       labels = c(\"Diesel\", \"Gasoline\")),\n    \n    municipality_type = factor(municipality_type,\n                               levels = c(\"I\", \"C\", \"IS\"),\n                               labels = c(\"Inland\", \n                                          \"Coastal\", \n                                          \"Islands\")),\n    \n    circulation_area = factor(circulation_area,\n                              levels = c(\"U\", \"R\"),\n                              labels = c(\"Urban\", \"Rural\")),\n    \n    year = factor(year)\n  )\n```\n:::\n\n\n### 4.5 Deriving Loss Ratio and Filtering Invalid Records\n\nTwo data quality issues are addressed in this step. First, records with `total_premium == 0` or `total_exposure == 0` are removed, as these represent policies with no meaningful risk exposure and would distort any rate or ratio calculations. Second, a new variable `loss_ratio` is derived by dividing `total_incurred` by `total_premium`. The loss ratio is a standard actuarial metric that measures claims cost as a proportion of premium earned (a value above 1.0 indicates that claims exceeded the premium collected for that policy).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_selected %>%\n  filter(total_premium > 0, total_exposure > 0) %>%\n  mutate(loss_ratio = total_incurred / total_premium)\n```\n:::\n\n\n### 4.6 Overview of Cleaned Dataset\n\nThe final cleaned dataset `insurance_clean` is inspected using `glimpse()` to verify that all variables are correctly typed and that the newly derived `loss_ratio` column has been appended. This serves as a final sanity check before proceeding to exploratory analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(insurance_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,091\nColumns: 18\n$ insured_id        <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7…\n$ year              <fct> 2022, 2022, 2023, 2024, 2022, 2023, 2024, 2022, 2023…\n$ policy_type       <fct> Comprehensive (excess), Comprehensive (excess), Comp…\n$ policy_status     <fct> Cancelled, Active, Active, Active, Active, Active, A…\n$ business_type     <fct> New Business, Portfolio, Portfolio, Portfolio, New B…\n$ payment_frequency <fct> Annual, Annual, Annual, Annual, Semiannual, Semiannu…\n$ bonus_score       <fct> Good, Good, Good, Good, Good, Good, Good, Good, Good…\n$ driver_age        <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39, 40, 41, …\n$ vehicle_age       <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20, 21, 22, …\n$ fuel_type         <fct> Gasoline, Diesel, Diesel, Diesel, Diesel, Diesel, Di…\n$ vehicle_value     <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 51626.66, 5…\n$ municipality_type <fct> Inland, Inland, Inland, Inland, Inland, Inland, Inla…\n$ circulation_area  <fct> Urban, Urban, Urban, Urban, Rural, Rural, Rural, Rur…\n$ total_premium     <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 687.4905, 69…\n$ total_claims      <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0…\n$ total_incurred    <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.000, 0.000…\n$ total_exposure    <dbl> 0.09863014, 1.00000000, 1.00000000, 1.00000000, 1.00…\n$ loss_ratio        <dbl> 0.0000000, 0.0000000, 0.4246231, 4.4239104, 0.000000…\n```\n\n\n:::\n:::\n\n\n## 5. Univariate Analysis\n\nUnivariate analysis examines each variable in isolation to understand its distribution central tendency, and spread. This section is organised into four sub-sections: policy characteristics, risk and geographic characteristics, driver and vehicle numerical variables, and financial variables. Together, they establish the foundational understanding of the portfolio's composition before proceeding to bivariate investigation.\n\n### 5.1 Policy Characteristics\n\nBar charts are used to visualise the distribition of categorical policy variables. Each chart is ordered by frequency to aid comparison, and proportopms are labelled directly on the bards using `scales::percent_format()`. The five charts are assembled into a single figure using `patchwork`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npct_bar <- function(data, var, fill_color, title) {\n  data %>%\n    count({{ var }}) %>%\n    mutate(pct = n / sum(n),\n           {{ var }} := fct_reorder({{ var }}, n)) %>%\n    ggplot(aes(x = {{ var }}, y = pct)) +\n    geom_col(fill = fill_color, width = 0.7) +\n    geom_text(aes(label = percent(pct, accuracy = 0.1)),\n              hjust = -0.1, size = 3.2) +\n    scale_y_continuous(labels = percent_format(),\n                       expand = expansion(mult = c(0, 0.18))) +\n    coord_flip() +\n    labs(title = title, x = NULL, y = \"Proportion\") +\n    theme_minimal(base_size = 11) +\n    theme(plot.title = element_text(size = 10, face = \"bold\"))\n}\n\np1 <- pct_bar(insurance_clean, policy_type,       \"#4E79A7\", \"Policy Type\")\np2 <- pct_bar(insurance_clean, policy_status,     \"#F28E2B\", \"Policy Status\")\np3 <- pct_bar(insurance_clean, business_type,     \"#59A14F\", \"Business Type\")\np4 <- pct_bar(insurance_clean, payment_frequency, \"#E15759\", \"Payment Frequency\")\np5 <- pct_bar(insurance_clean, bonus_score,       \"#76B7B2\", \"Bonus Score\")\n\n(p1 | p2 | p3) / (p4 | p5 | plot_spacer()) +\n  plot_annotation(\n    title    = \"Figure 5.1: Distribution of Policy Characteristics\",\n    theme    = theme(plot.title = element_text(size = 13, face = \"bold\"))\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/cat-policy-1.png){width=1152}\n:::\n:::\n\n\n- **Policy Type** - The portfolio is dominated by `Third-party + Combined` policies at 57.8%, indicating that most policyholders opt for third-party liability bundled with additional coverages such as theft, fire, or glass, rather than full comprehensive protection. `Comprehensive (excess)` is the second largest segment at 25.8%.\n\n- **Policy Status** - The dominance of `Active` policies at 89.2% confirms that the dataset captures a live book of business rather than a run-off portfolio.\n\n- **Business Type** - `New Business` accounts for 69.3% of policies — substantially outweighing `Portfolio` renewals at 30.7% — which suggests the insurer was in an active growth phase during 2022–2024, acquiring significantly more new customers than it was renewing existing ones.\n\n- **Payment Frequency** - `Annual` payment is by far the most common frequency at 81.3%, which simplifies exposure calculations as most policies represent full-year risk periods.\n\n- **Bonus Score** - Notably, 96.4% of policyholders carry a `Good` bonus score, indicating an exceptionally homogeneous portfolio in terms of prior claims experience, which may limit the discriminatory power of this variable in bivariate analysis.\n\n### 5.2 Risk and Geographic Characteristics\n\nThe same ordered bar chart approach is applied to risk segmentation and geographic variables, allowing the analyst to quickly identify dominant risk profiles within the portfolio.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np6 <- pct_bar(insurance_clean, fuel_type,         \"#B07AA1\", \"Fuel Type\")\np7 <- pct_bar(insurance_clean, municipality_type, \"#FF9DA7\", \"Municipality Type\")\np8 <- pct_bar(insurance_clean, circulation_area,  \"#9C755F\", \"Circulation Area\")\np9 <- pct_bar(insurance_clean, year,              \"#BAB0AC\", \"Policy Year\")\n\n(p6 | p7) / (p8 | p9) +\n  plot_annotation(\n    title = \"Figure 5.2: Distribution of Risk and Geographic Characteristics\",\n    theme = theme(plot.title = element_text(size = 13, face = \"bold\"))\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/cat-risk-1.png){width=960}\n:::\n:::\n\n\n- **Fuel Type** - `Diesel` vehicles account for 63.9% of the portfolio, nearly double the proportion of `Gasoline` vehicles at 35.7%, consistent with the historical dominance of `Diesel` engines in the Spanish private vehicle market during the coverage period. A small residual (`NA`) of 0.4% carries missing fuel type information — these correspond to the 1,287 records flagged during the missing value check in Section 4.2 that were retained in the dataset as a separate category.\n\n- **Municipality Type** - `Inland` municipalities represent the largest geographic segment at 64.6%, followed by `Coastal` at 28.6% and `Islands` at 6.8%, broadly reflecting the distribution of Spain's registered vehicle population away from peripheral regions.\n\n- **Circulation area** is more evenly split than expected, with `Urban` at 53.8% and `Rural` at 46.2% — the near-parity suggests the insurer operates across diverse driving environments, which has implications for claims frequency patterns that will be examined in Section 6.\n\n- **Policy Year** reveals a distinctly uneven distribution: `2024` accounts for 47.5% of records, `2023` for 33.6%, and `2022` for only 19.0%. This increasing concentration towards more recent years is consistent with a growing portfolio — as the insurer acquired more new business (noted at 69.3% in Section 5.1), the total policy count expanded year on year, and this temporal skew should be considered when interpreting any year-on-year comparisons.\n\n### 5.3 Driver and Vehicle Age\n\nRaincloud plots are employed to visualise the distributions of `driver_age` and `vehicle_age`. Both variables are established actuarial risk rating factors in motor insurance — driver age is a primary predictor of claims frequency, while vehicle age influences both repair costs and total loss probability. It combine three complementary layers: a half-density plot for the distributional shape, a boxplot for median and interquartile spread, and a dot strip for raw data density. This technique is implemented using the `ggdist` package and is preferred over a standard histogram because it simultaneously reveals the full distributional shape, central tendency, and spread without binning artefacts — making it particularly well-suited for continuous variables with sample sizes as large as this portfolio. `vehicle_value`, the third continuous risk variable, is examined in Section 6 in the context of its relationship with loss ratio.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np_dage <- insurance_clean %>%\n  ggplot(aes(x = driver_age, y = \"Driver Age\")) +\n  stat_halfeye(adjust = 0.5, width = 0.6, .width = 0,\n               justification = -0.3, point_colour = NA,\n               fill = \"#4E79A7\", alpha = 0.7) +\n  geom_boxplot(width = 0.15, outlier.shape = NA,\n               color = \"grey30\", fill = \"white\") +\n  stat_dots(side = \"left\", dotsize = 0.4,\n            justification = 1.1, binwidth = 0.8,overflow = \"compress\",\n            color = \"#4E79A7\", alpha = 0.3) +\n  coord_flip() +\n  labs(title = \"Driver Age\", x = \"Age (Years)\", y = NULL) +\n  theme_minimal(base_size = 11) +\n  theme(plot.title = element_text(face = \"bold\"))\n\np_vage <- insurance_clean %>%\n  ggplot(aes(x = vehicle_age, y = \"Vehicle Age\")) +\n  stat_halfeye(adjust = 0.5, width = 0.6, .width = 0,\n               justification = -0.3, point_colour = NA,\n               fill = \"#F28E2B\", alpha = 0.7) +\n  geom_boxplot(width = 0.15, outlier.shape = NA,\n               color = \"grey30\", fill = \"white\") +\n  stat_dots(side = \"left\", dotsize = 0.4,\n            justification = 1.1, binwidth = 0.8,overflow = \"compress\",\n            color = \"#F28E2B\", alpha = 0.3) +\n  coord_flip() +\n  labs(title = \"Vehicle Age\", x = \"Age (Years)\", y = NULL) +\n  theme_minimal(base_size = 11) +\n  theme(plot.title = element_text(face = \"bold\"))\n\np_dage / p_vage +\n  plot_annotation(\n    title    = \"Figure 5.3: Distribution of Driver Age and Vehicle Age\",\n    subtitle = \"Raincloud plots combining half-density, boxplot, and raw data dot strip\",\n    theme    = theme(plot.title    = element_text(size = 13, face = \"bold\"),\n                     plot.subtitle = element_text(size = 10))\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/raincloud-1.png){width=960}\n:::\n:::\n\n\n- **Driver age** spans roughly 20 to 85 years, with the boxplot revealing a median in the late 40s and an interquartile range stretching from approximately 37 to 57 years. The density layer confirms a broad, relatively symmetric distribution centred on middle-aged drivers, with a gradual taper at older ages. The near-absence of drivers below 25 reflects the deterrent effect of high insurance premiums for young drivers in this market segment.\n- **Vehicle age** displays a markedly different profile — the median sits around 25 years with a right-skewed distribution extending beyond 60 years, indicating a substantial tail of ageing vehicles in the portfolio. This long tail carries meaningful actuarial implications: older vehicles are more susceptible to total loss claims relative to their declared value, which can disproportionately inflate the loss ratio for that segment.\n- The dot strip on both plots confirms high data density across the core age ranges, with progressive thinning towards the extremes — a pattern consistent with the natural age distribution of both drivers and vehicle fleets.\n\n### 5.4 Financial Variables\n\n`gghistostats()` from the `ggstatsplot` package is used to examine the distributions of `total_premium` and `loss_ratio`. Unlike a standard histogram, `gghistostats()` enriches the display with three additions: a fitted normal distribution curve as a visual reference for assessing symmetry and normality, a statistical subtitle reporting a one-sample t-test with effect size, and descriptive statistics including the mean and standard deviation. This allows both the shape and the central tendency of each distribution to be communicated within a single figure. Given the nature of insurance data — where the majority of policies generate no claims — both variables are expected to be strongly right-skewed and zero-inflated, making the departure from the normal curve visually informative. For `loss_ratio`, records above 5.0 (i.e., claims exceeding five times the premium collected) are excluded from the visualisation only, as these extreme outliers compress the histogram scale and obscure the distributional shape for the vast majority of policies.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np_prem <- gghistostats(\n  data       = insurance_clean,\n  x          = total_premium,\n  xlab       = \"Total Premium (€)\",\n  title      = \"Distribution of Total Premium\",\n  fill.color = \"#4E79A7\",\n  normal.curve = TRUE,\n  normal.curve.args = list(color = \"darkred\", linewidth = 1)\n)\n\np95_lr <- quantile(insurance_clean$loss_ratio[insurance_clean$loss_ratio > 0], 0.95)\n\np_lr_claims <- gghistostats(\n  data       = insurance_clean %>% filter(loss_ratio > 0, loss_ratio <= p95_lr),\n  x          = loss_ratio,\n  xlab       = \"Loss Ratio (claims-positive, capped at 95th percentile)\",\n  title      = \"Loss Ratio — Claims-Positive Policies\",\n  fill.color = \"#E15759\",\n  normal.curve = TRUE,\n  normal.curve.args = list(color = \"darkred\", linewidth = 1)\n)\n\n(p_prem | p_lr_claims) +\n  plot_annotation(\n    title    = \"Figure 5.4: Distributional analysis of Total Premium and Loss Ratio\",\n    theme    = theme(plot.title    = element_text(size = 13, face = \"bold\"),\n                     plot.subtitle = element_text(size = 10))\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/histostats-1.png){width=1152}\n:::\n:::\n\n\nTotal premium follows a strongly right-skewed distribution with a mean of €296.76, confirming the mean is statistically and practically different from zero. The bulk of policies are concentrated in the €200 to €500 range, consistent with standard third-party and combined coverage pricing in the SPanish motor market. The long right tail extending beyond €3,000 reflects a segment of high-value or high-coverage vehicles attracting substantially elevated premiums. THe normal curve overlay confirms strong non-normality, a finding relevant to the choice of non-parametric and robust statistical methods in Section 6.\n\nOf the 354,091 policies in the cleaned dataset, 42,263 (11.9%) recorded at least one claim with a non-zero incurred loss. The remaining 88.1% reported a loss ratio of zero. The loss ratio chart is restricted to these 42,263 claims-positive policies, and further capped at the 95th percentile (loss ratio = 19.48) to prevent the extreme upper tail from compressing the visualisation. THe excluded 5% reaching a maximum of 11,348, represent huge loss events where policies incurred large claims. Within the visualised 95th percentile of the claims-bearing policies, the mean loss ratio is 3.23, indicating that on average, claims costs were 323% of the premium collected. The distribution peaks in the 0 to 0.5 range but remains elevated across the full spectrum, indicating that large loss events are common rather than exceptional among claims-bearing policies. This combination of relatively low claims frequency (11.9%) but high average severity is the defining risk characteristic of the portfolio and motivates the bivariate investigation in Section 6.\n\n## 6. Bivariate Analysis\n\nBuilding on the univariate findings in Section 5, this section investigates relationships between key risk factors and the loss ratio to identify variables that statistically influence portfolio profitability and volatility. All analyses involving loss ratio are restricted to claims-positive policies (loss_ratio \\> 0) and capped at the 95th percentile (loss_ratio ≤ 19.48) - this is consistent with the approach in Section 5.4, to remove extreme outliers so as to not distort the visualisation. Given the confirmed non-normality of loss ratio in Section 5.4, non-parametric tests are applied throughout.\n\n### 6.1 Policy Factors vs Loss Ratio\n\n`ggbetweenstats()` from `ggstatsplot` is used to examine whether loss ratio differs significantly across policy type and business type. This function combines a violin plot, box plot and individual data points in a single dispplay, and annotates th chart with Kruskal-Wallis test result and effect size for vairables with three or more groups, and Mann-Whitney for binary variables. Policy type is examined first as it represents the most fundamental segmentation of the portfolio, as different coverage structures carry inherently different risk profiles and premium bases, which would be expected to produce different loss ratio distributions. Business type is examined to determine whether new business and portfolio renewals differ systematically in their claims experience, a common underwriting question in non-life insurance.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlr_data <- insurance_clean %>%\n  filter(loss_ratio > 0, loss_ratio <= p95_lr)\n\np_policy_type <- ggbetweenstats(\n  data             = lr_data,\n  x                = policy_type,\n  y                = loss_ratio,\n  type             = \"nonparametric\",\n  title            = \"Loss Ratio by Policy Type\",\n  xlab             = \"Policy Type\",\n  ylab             = \"Loss Ratio\",\n  pairwise.display = \"significant\",\n  p.adjust.method  = \"bonferroni\"\n) + coord_cartesian(ylim = c(0, 10))\n\np_business_type <- ggbetweenstats(\n  data    = lr_data,\n  x       = business_type,\n  y       = loss_ratio,\n  type    = \"nonparametric\",\n  title   = \"Loss Ratio by Business Type\",\n  xlab    = \"Business Type\",\n  ylab    = \"Loss Ratio\"\n) + coord_cartesian(ylim = c(0, 10))\n\n(p_policy_type | p_business_type) +\n  plot_annotation(\n    title    = \"Figure 6.1: Loss Ratio by Policy Type and Business Type\",\n    theme    = theme(plot.title    = element_text(size = 13, face = \"bold\"),\n                     plot.subtitle = element_text(size = 10))\n  )\n```\n\n::: {.cell-output-display}\n![Loss Ratio by Policy Type and Business Type](Take-Home_Ex01_files/figure-html/unnamed-chunk-2-1.png){width=1344}\n:::\n:::\n\n\nThe Kruskal-Wallis test confirms that loss ratio differs significantly across policy types. Post-hoc Dunn tests with Bonferroni adjustment reveal that all pairwise comparisons are significant, indicating each policy type occupies a genuinely distinct loss ratio position. Third-party-only policies record the highest median loss ratio at 4.56 (an expected finding as this segment carries the lowest premiums while remaining exposed to unlimited third-party liability claims, meaning even modest claims produce high loss ratios relative to premium. Third-party + Glass and Third-party + Combined policies cluster in the mid-range (medians 2.45 and 2.47 respectively), while Comprehensive coverage (both with and without excess) records the lowest median loss ratios (1.88 and 1.85), reflecting the higher premium base that provides a greater buffer against claims costs. The violin shapes further reveal that comprehensive policies have a more concentrated distribution, while third-party variants show greater spread — indicating higher volatility in addition to higher central loss.\n\nNew business policies carry a statistically and significantly higher median loss ratio (2.29) than portfolio renewals (2.01), confirmed by the Mann-Whitney test (p \\< 0.001). The directional finding is consistent with the adverse selection hypothesis in insurance underwriting — newly acquired customers have less established claims history and may carry undisclosed risk factors not yet reflected in their pricing, resulting in higher realised loss ratios compared to seasoned portfolio policyholders whose risk profiles are better understood.\n\n### 6.2 Bonus Score and Circulation Area vs Loss Ratio\n\nThis section extends the bivariate analysis to two additional categorical risk dimensions: `bonus score` and `circulation area`. `Bonus score` is an ordinal variable capturing the policyholder's accumulated no-claims discount history (higher scores reflect longer claim-free experience and are typically associated with lower-risk drivers). `Circulation area` classifies the geographic region in which the vehicle is primarily operated, a proxy for exposure to traffic density, road conditions, and regional claims frequency. Both variables are expected to exhibit systematic differences in loss ratio, and the Kruskal-Wallis test with post-hoc Dunn comparisons is applied consistently with the non-parametric framework established in Section 6.1.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# ── Section 6.2: Bonus Score and Circulation Area vs Loss Ratio ──────────────\n\n# 6.2a: Bonus Score vs Loss Ratio\np6_2a <- ggbetweenstats(\n  data            = lr_data,\n  x               = bonus_score,\n  y               = loss_ratio,\n  type            = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  pairwise.display     = \"significant\",\n  p.adjust.method      = \"bonferroni\",\n  title           = \"Loss Ratio by Bonus Score\",\n  xlab            = \"Bonus Score\",\n  ylab            = \"Loss Ratio\",\n  package         = \"RColorBrewer\",\n  palette         = \"Set2\",\n  violin.args     = list(width = 0.6, alpha = 0.3),\n  point.args      = list(alpha = 0.05, size = 0.8),\n  centrality.point.args = list(size = 4),\n  ggtheme         = theme_minimal(base_size = 11)\n) +\n  coord_cartesian(ylim = c(0, 10)) +\n  theme(\n  plot.title   = element_text(face = \"bold\", hjust = 0.5),\n  plot.margin  = margin(t = 10, r = 10, b = 20, l = 10)\n)\n\n# 6.2b: Circulation Area vs Loss Ratio\np6_2b <- ggbetweenstats(\n  data            = lr_data,\n  x               = circulation_area,\n  y               = loss_ratio,\n  type            = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  pairwise.display     = \"significant\",\n  p.adjust.method      = \"bonferroni\",\n  title           = \"Loss Ratio by Circulation Area\",\n  xlab            = \"Circulation Area\",\n  ylab            = \"Loss Ratio\",\n  package         = \"RColorBrewer\",\n  palette         = \"Set3\",\n  violin.args     = list(width = 0.6, alpha = 0.3),\n  point.args      = list(alpha = 0.05, size = 0.8),\n  centrality.point.args = list(size = 4),\n  ggtheme         = theme_minimal(base_size = 11)\n) +\n  coord_cartesian(ylim = c(0, 10)) +\n  theme(\n  plot.title   = element_text(face = \"bold\", hjust = 0.5),\n  plot.margin  = margin(t = 10, r = 10, b = 20, l = 10)\n)\n\n# ── Combined layout ───────────────────────────────────────────────────────────\np6_2a / p6_2b +\n  plot_layout(heights = c(1, 1)) +\n  plot_annotation(\n    title    = \"Figure 6.2: Loss Ratio by Bonus Score and Circulation Area\",\n    caption = \"Claims-positive policies, loss ratio capped at 95th percentile (19.48)\\nKruskal-Wallis test; post-hoc Dunn with Bonferroni correction\",\n    theme   = theme(\n      plot.title   = element_text(face = \"bold\", size = 13, hjust = 0.5),\n      plot.caption = element_text(size = 9, colour = \"grey50\")\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-3-1.png){width=768}\n:::\n:::\n\n\nThe Kruskal-Wallis test confirms a statistically significant difference in loss ratio across bonus score groups (p \\< 0.001). The directional finding is, however, counter-intuitive: policyholders classified as \"Good\" record the highest median loss ratio (2.19), while \"Neutral\" (1.72) and \"Bad\" (1.55) record progressively lower medians. Post-hoc Dunn tests with Bonferroni correction confirm that all pairwise differences are significant. This reversal of the expected gradient is consistent with a premium denominator effect — \"Good\" bonus score holders have accumulated no-claims discounts that reduce their charged premium; with a smaller premium denominator, even moderate claims produce elevated loss ratios. Conversely, policyholders in the \"Bad\" category are likely subject to claim-loaded premiums or surcharges, inflating the denominator and suppressing the ratio. The extreme group size imbalance — Good (n = 38,154) versus Bad (n = 883) — warrants caution: the \"Bad\" and \"Neutral\" estimates carry considerably higher sampling uncertainty despite statistical significance.\n\nCirculation area shows a statistically significant but practically negligible difference in loss ratio between urban and rural policyholders (p \\< 0.001). Rural policies record a marginally higher median loss ratio (2.25) compared to urban policies (2.11). Despite the counter-intuitive expectation that urban driving — with higher traffic density and collision frequency — would produce worse loss outcomes, rural policyholders may face higher severity-per-claim costs driven by greater travel distances, delayed emergency response, and higher vehicle repair logistics costs. The violin shapes across both groups are broadly similar in spread, and the negligible effect size indicates that circulation area alone is a weak differentiator of loss ratio at the portfolio level.\n\n### 6.3 Driver Age, Vehicle Age and Vehicle Value vs Loss Ratio\n\nThis section examines the relationship between loss ratio and three continuous risk-rating variables: driver age, vehicle age, and vehicle value. Scatter plots with marginal distributions are produced using `ggscatterstats()`, with Spearman's rank correlation applied consistently with the non-parametric framework used throughout Section 6. Driver age captures the experience and risk profile of the insured, vehicle age reflects depreciation and mechanical reliability, and vehicle value serves as a proxy for repair and replacement costs. Where statistically significant correlations exist, the direction and magnitude of association are interpreted in the context of pricing expectations.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# ── Section 6.3: Continuous Variables vs Loss Ratio ───────────────────────────\n\n# 6.3a: Driver Age vs Loss Ratio\np6_3a <- ggscatterstats(\n  data    = lr_data,\n  x       = driver_age,\n  y       = loss_ratio,\n  type    = \"nonparametric\",\n  marginal = FALSE, \n  title   = \"Driver Age vs Loss Ratio\",\n  xlab    = \"Driver Age (years)\",\n  ylab    = \"Loss Ratio\",\n  point.args       = list(alpha = 0.05, size = 0.8, colour = \"steelblue\"),\n  smooth.line.args = list(method = \"lm\", colour = \"firebrick\", se = TRUE),\n  ggtheme = theme_minimal(base_size = 11)\n) +\n  coord_cartesian(ylim = c(0, 10)) +\n  theme(plot.title = element_text(face = \"bold\", hjust = 0.5))\n\n# 6.3b: Vehicle Age vs Loss Ratio\np6_3b <- ggscatterstats(\n  data    = lr_data,\n  x       = vehicle_age,\n  y       = loss_ratio,\n  type    = \"nonparametric\",\n  marginal = FALSE,\n  title   = \"Vehicle Age vs Loss Ratio\",\n  xlab    = \"Vehicle Age (years)\",\n  ylab    = \"Loss Ratio\",\n  point.args       = list(alpha = 0.05, size = 0.8, colour = \"steelblue\"),\n  smooth.line.args = list(method = \"lm\", colour = \"firebrick\", se = TRUE),\n  ggtheme = theme_minimal(base_size = 11)\n) +\n  coord_cartesian(ylim = c(0, 10)) +\n  theme(plot.title = element_text(face = \"bold\", hjust = 0.5))\n\n# 6.3c: Vehicle Value vs Loss Ratio\np6_3c <- ggscatterstats(\n  data    = lr_data,\n  x       = vehicle_value,\n  y       = loss_ratio,\n  type    = \"nonparametric\",\n  marginal = FALSE,\n  title   = \"Vehicle Value vs Loss Ratio\",\n  xlab    = \"Vehicle Value\",\n  ylab    = \"Loss Ratio\",\n  point.args       = list(alpha = 0.05, size = 0.8, colour = \"steelblue\"),\n  smooth.line.args = list(method = \"lm\", colour = \"firebrick\", se = TRUE),\n  ggtheme = theme_minimal(base_size = 11)\n) +\n  coord_cartesian(ylim = c(0, 10)) +\n  theme(plot.title = element_text(face = \"bold\", hjust = 0.5))\n\n# ── Combined layout ───────────────────────────────────────────────────────────\n(p6_3a / p6_3b / p6_3c) +\n  plot_annotation(\n    title   = \"Figure 6.3: Loss Ratio vs Continuous Risk Variables\",\n    caption = \"Claims-positive policies, loss ratio capped at 95th percentile (19.48)\\nSpearman rank correlation; n = 40,149\",\n    theme   = theme(\n      plot.title   = element_text(face = \"bold\", size = 13, hjust = 0.5),\n      plot.caption = element_text(size = 9, colour = \"grey50\")\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-4-1.png){width=864}\n:::\n:::\n\n\nSpearman rank correlations reveal markedly different patterns across the three continuous risk variables examined.\n\nDriver age shows a statistically significant but practically negligible positive association with loss ratio (ρ = 0.02, p \\< 0.001). The regression line is essentially flat across the full age range, and the vertical striping in the scatter — a natural artefact of age being recorded in whole years — confirms that no meaningful gradient exists. Driver age alone is a poor predictor of loss ratio in this portfolio, suggesting that age-related risk differences are already being absorbed through pricing or policy type selection.\n\nVehicle age similarly yields a negligible correlation (ρ = 0.01, p = 0.004). The near-horizontal regression line indicates that older vehicles do not systematically produce higher or lower loss ratios relative to newer ones — consistent with the possibility that older vehicles carry lower insured values and therefore lower premiums that offset any increase in mechanical claim frequency.\n\nVehicle value is the only variable in this section to demonstrate a substantively meaningful association (ρ = −0.10, p \\< 0.001). The negative correlation indicates that higher-value vehicles are associated with lower loss ratios — a premium denominator effect consistent with actuarial expectations. Higher-value vehicles attract larger premiums, providing a greater buffer against claims costs relative to the premium base. Additionally, owners of higher-value vehicles may occupy lower-risk demographic and behavioural profiles. The steep left-skew in the vehicle value distribution confirms that most policies are concentrated below 50,000, where loss ratio variance is highest, while the sparse high-value tail shows progressively lower and less variable loss ratios.\n\nAcross all three variables, loss ratio in this portfolio is driven more by policy structure and coverage type (as shown in Section 6.1) than by individual driver or vehicle characteristics in isolation.\n\n### 6.4 Correlation Matrix with `ggpairs()`\n\nThis section presents a correlation matrix across all continuous variables in the analysis using `ggpairs()` from the GGally package. This provides a holistic view of bivariate relationships — combining scatter plots, density curves, and Spearman correlation coefficients in a single display. The matrix allows simultaneous inspection of variable-to-variable associations, helping to confirm the direction and relative strength of each variable's relationship with loss ratio.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# ── Section 6.4: Correlation Matrix ──────────────────────────────────────────\n\n# Select continuous variables of interest\nlr_pairs <- lr_data |>\n  select(driver_age, vehicle_age, vehicle_value, total_premium, loss_ratio)\n\nggpairs(\n  lr_pairs,\n  columnLabels = c(\"Driver Age\", \"Vehicle Age\", \n                   \"Vehicle Value\", \"Total Premium\", \"Loss Ratio\"),\n  upper = list(continuous = wrap(\"cor\", \n                                 method = \"spearman\", \n                                 size   = 4)),\n  lower = list(continuous = wrap(\"smooth\",\n                                 alpha  = 0.02,\n                                 size   = 0.3,\n                                 method = \"lm\")),\n  diag  = list(continuous = wrap(\"densityDiag\",\n                                 fill  = \"steelblue\",\n                                 alpha = 0.4)),\n  progress = FALSE\n) +\n  labs(\n    title   = \"Figure 6.4: Correlation Matrix of Continuous Risk Variables\",\n    caption = \"Claims-positive policies, loss ratio capped at 95th percentile (19.48)\\nSpearman rank correlation\"\n  ) +\n  theme_minimal(base_size = 10) +\n  theme(\n    plot.title   = element_text(face = \"bold\", size = 13, hjust = 0.5),\n    plot.caption = element_text(size = 9, colour = \"grey50\"),\n    strip.text   = element_text(face = \"bold\", size = 9)\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-5-1.png){width=1152}\n:::\n:::\n\n\nThe correlation matrix presents Spearman rank correlations across five continuous variables, with regression-smoothed scatter plots in the lower triangle and univariate density curves on the diagonal.\n\nThe most striking finding is the near-perfect positive correlation between driver age and vehicle age (ρ = 0.858, p \\< 0.001), visible in the lower-left scatter as a near-diagonal band. This indicates strong multicollinearity — older drivers systematically operate older vehicles in this portfolio. As a consequence, these two variables should not be treated as independent predictors in any downstream modelling without careful handling, as their effects on loss ratio cannot be cleanly separated.\n\nAmong the predictors of loss ratio, total premium shows the strongest association (ρ = −0.321, p \\< 0.001), confirming that higher premiums are paradoxically associated with lower realised loss ratios. This is consistent with the premium denominator effect: higher premiums inflate the denominator of the loss ratio calculation, compressing the ratio even when claims costs are elevated. Vehicle value shows a weaker but meaningful negative association with loss ratio (ρ = −0.101, p \\< 0.001), corroborating the finding from Section 6.3. The moderate correlation between vehicle value and total premium (ρ = 0.365, p \\< 0.001) is expected, as higher-value vehicles attract higher insured sums and therefore larger premiums.\n\nDriver age and vehicle age both show negligible correlations with loss ratio (ρ = 0.021 and 0.014 respectively), consistent with Section 6.3 findings. The diagonal density plots further confirm the heavy right-skew in vehicle value, total premium, and loss ratio — reinforcing the appropriateness of non-parametric methods used throughout Section 6.\n\n## 7. Summary\n\nThis analysis examined a motor insurance portfolio of **354,091 policies** using exploratory data analysis and non-parametric inferential statistics. The primary outcome variable — **loss ratio** (total incurred claims ÷ total premium) — was restricted to claims-positive policies and capped at the **95th percentile (19.48)** to mitigate the influence of extreme outliers, yielding an analytical dataset of **40,149 policies**.\n\n### 7.1 Policy Structure Drives Loss Ratio\n\n- **Policy type is the dominant structural driver of loss ratio** (p \\< 0.001). Third-party-only policies record the highest median loss ratio (**4.56**), driven by minimal premium bases combined with unlimited liability exposure. Comprehensive policies — both with and without excess — record the lowest medians (**1.85 to 1.88**), reflecting the premium buffer that broader coverage commands.\n\n- **New business policies carry systematically higher loss ratios than renewals** (2.29 vs 2.01, p \\< 0.001), consistent with adverse selection — newly acquired customers have less established claims histories and carry undisclosed risk factors not yet reflected in their pricing.\n\n### 7.2 Counter-Intuitive Findings\n\nTwo findings run against intuitive expectations.\n\n- First, policyholders with **\"Good\" bonus scores record the highest median loss ratio (2.19)**, not the lowest — most plausibly explained by the **premium denominator effect**, whereby accumulated no-claims discounts compress the premium base and inflate the ratio.\n\n- Second, **rural policyholders show marginally higher loss ratios than urban ones** (2.25 vs 2.11), suggesting higher per-claim severity rather than frequency.\n\n### 7.3 Continuous Predictors: Premium Dominates\n\nAmong continuous variables, **total premium is the strongest predictor of loss ratio (ρ = −0.321)** — again reflecting the denominator mechanism. Vehicle value shows a smaller but meaningful negative association (ρ = −0.101). By contrast, **driver age and vehicle age are effectively uncorrelated with loss ratio** (ρ ≈ 0.02 and 0.01 respectively).\n\n> ⚠️ **Multicollinearity Alert:** Driver age and vehicle age are near-perfectly correlated (ρ = 0.858) and cannot be treated as independent predictors in any downstream modelling.\n\n### 7.4 Conclusion\n\n> Loss ratio in this portfolio is shaped primarily by **policy structure and premium adequacy** — not by individual policyholder or vehicle characteristics in isolation. Coverage type and premium level remain the most actionable levers for profitability management. Demographic variables such as driver age provide limited marginal information beyond what policy structure already captures.\n\n## Bonus Section: Ridgeline Plot: Loss Ratio by Year\n\nAs a supplementary visualisation, Figure B.1 presents the distribution of loss ratio across policy years using a ridgeline plot from the ggridges package. Ridgeline plots are particularly effective for displaying distributional change over time, allowing simultaneous comparison of shape, central tendency, and spread across multiple years without the clutter of overlapping boxplots. This plot reveals whether portfolio-level loss ratio has shifted structurally over the observation period — a key diagnostic for monitoring underwriting cycle trends.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# ── Bonus: Ridgeline Plot — Loss Ratio by Year ────────────────────────────────\n\nlr_data |>\n  mutate(year = factor(year)) |>  \n  ggplot(aes(x     = loss_ratio,\n             y     = year,\n             fill  = year,\n             colour = year)) +\n  geom_density_ridges(\n    alpha         = 0.6,\n    scale         = 0.8,\n    rel_min_height = 0.01,\n    bandwidth     = 0.15\n  ) +\n  scale_x_continuous(limits = c(0, 10),\n                     breaks = seq(0, 10, by = 2)) +\n  scale_fill_viridis_d(option = \"mako\", direction = -1) +\n  scale_colour_viridis_d(option = \"mako\", direction = -1) +\n  labs(\n    title   = \"Figure B.1: Loss Ratio Distribution by Policy Year\",\n    x       = \"Loss Ratio\",\n    y       = \"Policy Year\",\n    caption = \"Claims-positive policies, loss ratio capped at 95th percentile (19.48)\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title   = element_text(face = \"bold\", size = 13, hjust = 0.5),\n    plot.caption = element_text(size = 9, colour = \"grey50\"),\n    legend.position = \"none\"\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\nThis ridgeline plot reveals meaningful year-on-year shifts in the loss ratio distribution across the three policy years represented in the portfolio (2022–2024).\n\nThe 2024 distribution (dark) exhibits the sharpest and most concentrated peak, situated close to zero, with a steep drop-off and a relatively thin right tail. This pattern warrants careful interpretation — while it may suggest improving portfolio profitability in the most recent year, it is more likely a consequence of claims development lag. Policies written in 2024 have had less time for claims to be reported, assessed, and settled; incurred amounts are therefore understated relative to their ultimate cost, artificially compressing loss ratios for the most recent cohort.\n\nThe 2023 distribution (blue) shows a broader peak and a more pronounced secondary shoulder around loss ratios of 3–4, indicating a more mature claims profile with a greater proportion of policies reaching higher realised loss outcomes. The right tail is heavier than 2024, consistent with more complete claims development.\n\nThe 2022 distribution (green) is the flattest and most spread across the full range — reflecting the most mature claims cohort in the dataset, where a greater share of incurred costs have been reported and settled. The flatter mode and heavier spread indicate higher aggregate claims burden relative to premium compared to the appearance of more recent years.\n\nTogether, the ridgeline confirms that cross-year comparisons of loss ratio must account for claims development maturity. A rising loss ratio from 2022 to 2024 would be misread as deterioration when it in fact reflects the natural run-off pattern of an insurance portfolio — a consideration critical to any longitudinal profitability assessment.\n",
    "supporting": [
      "Take-Home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}